# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://slienceme.cn
date_format: "ordinal"
title: Slience_me的博客
subtitle: "slience_me的博客"
description: "slience_me的个人博客"
keywords: slience_me, Slience_me, slience-me, slienceme
timezone: Asia/Shanghai
encoding: "utf-8"
# 页面左下角显示的年份
since: 2020-2025
# 源码仓库，请替换成自己的
repository: slience-me/slienceme.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: false
# 可选组件配置
components:
    # 分享
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: true
        hide-platforms: qq,facebook
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2024-12-01
    # My Popular Repositories
    side_bar_repo:
        enabled: true
        limit: 5
    # 文章字数统计
    word_count:
        enabled: true
    # 页面右上角，以及「关于」页面的二维码
    # 修改图片请替换 assets/images/qrcode.jpg
    #    qrcode:
    #        enabled: true
    #        image_alt: Slience_me
    # 维基索引页使用哪种视图，支持 列表（list）/分类（cate）
    wiki:
        view: cate
    # 图片灯箱效果功能
    fancybox:
        enabled: false
# 压缩页面内容
compress_html:
  clippings: 全部
  comments: ["<!--", "-->"]
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: slience_me
organization:
organization_url: 
github_username: slience-me
location: Tianjin, China
email: slienceme520@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档
    mobile-hidden: true

  -
    href: /open-source/
    label: 开源
    mobile-hidden: true

  -
    href: /fragments/
    label: 片段

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接
    mobile-hidden: true

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
    fragments:
        output: true
        permalink: /fragment/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk, utterances, beaudar, giscus
comments_provider: giscus
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# disqus 配置参考：https://disqus.com
disqus:
    username: 
# gitment 配置参考：https://imsun.net/posts/gitment-introduction/
gitment:
    owner: slience-me
    repo: slience-me-gitment
    oauth:
        client_id: 384c321be0e44d3b2efb
        client_secret: aed0dc53dee53855bba858b551792bd7caf95a67
# gitalk 配置参考：https://github.com/gitalk/gitalk#install
gitalk:
    owner: slience-me
    repo: slience-me/blog-comments
    clientID: 8d7ae8a570a4a80b9a40
    clientSecret: 99669a3cca565984ff9c2391254ff314ba95f115
# utterances 配置参考：https://utteranc.es/
utterances:
    repo: slience-me/blog-comments
# beaudar 配置参考：https://beaudar.lipk.org/
beaudar:
    repo: slience-me/blog-comments
# giscus 配置参考：https://giscus.app/zh-CN
giscus:
    repo: slience-me/blog-comments
    repo-id: MDEwOlJlcG9zaXRvcnk5MzEyNzkxNw==
    category: Announcements
    category-id: DIC_kwDOBY0E7c4CRtg9
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: # G-20FLEG5Q2W
    adsense:
        enabled: false
        footer: false
        sidebar: false
        sidebar-detail: false
        content_header: false
        content_footer: false
