name: Build 和 Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Set Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install and Build
        run: |
          gem install bundler
          bundle install
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages-${{ github.run_id }}  # 保证 artifact 名称唯一

      - name: Check _site folder contents  # 可选，检查 _site 文件夹内容
        run: ls -la _site

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: built
          FOLDER: _site
          CLEAN: true
